# Generated by Django 3.1.4 on 2020-12-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201228_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visit_counter',
            field=models.IntegerField(default=0, max_length=2, verbose_name='The number of visits'),
        ),
    ]
